export const USER_LOG = 'USER_LOG';
export const USER_FAIL = 'USER_FAIL';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGOUT_POPUP = 'LOGOUT_POPUP';
export const SET_CURRENT_ALL_USER = 'SET_CURRENT_ALL_USER';
export const CLEAR_AUTH = 'CLEAR_AUTH';
export const USER_LOGOUT = 'USER_LOGOUT';
export const ERROR_LOGIN = 'ERROR_LOGIN';

export const GET_ME = 'GET_ME';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

export const SIDEBAR_HAMBURGER = 'SIDEBAR_HAMBURGER';

export const TASK_CARD_USER_PROFILE = 'TASK_CARD_USER_PROFILE';

export const SET_CURRENT_MY_ALLTASKS = 'SET_CURRENT_MY_ALLTASKS';

export const SET_CURRENT_MY_DEPARTMENT_TASKS =
  'SET_CURRENT_MY_DEPARTMENT_TASKS';

export const ERROR_ALL_TASKS = 'ERROR_ALL_TASKS';
export const SET_CURRENT_ALL_TASKS = 'SET_CURRENT_ALL_TASKS';
export const FILTER_ALL_TASKS = 'FILTER_ALL_TASKS';

export const TASK_CARD_DETAIL = 'TASK_CARD_DETAIL';

export const CLEAR_ALL_POPUP = 'CLEAR_ALL_POPUP';

export const SEARCH_TASK = 'SEARCH_TASK';

export const SPLICE_ONE_TASK = 'SPLICE_ONE_TASK';
export const SET_CURRENT_ONE_TASK = 'SET_CURRENT_ONE_TASK';

export const TASK_CREATE = 'TASK_CREATE';
